name: cashing and artifact

on: [workflow_dispatch]

jobs:
    use-axios:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 #installing axios so its avaialbe in next steps
            - name: install dependency
              run: npm install 
            - name: Use Axions # axios is use to send request
              uses: actions/github-script@v6
              with:
                script: |
                    const axios = require('axios')
                    const res = await axios('https://icanhazdadjoke.com', {headers: {
                        Accept: 'text/plain'}})
                    console.log(res.data)

            
              
