name: cashing and artifact

on: [workflow_dispatch]

jobs:
    use-axios:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 #installing axios so its avaialbe in next steps
            - name: use cache action
              id: cache
              uses: actions/cache@v3
              with:
                path: "~/.npm"
                key: "npm-cache"
            - name: display cache
              run: echo '${{toJson(steps.cache.outputs)}}'
            - name: install dependency
              run: npm install 
            - name: Use Axios # axios is use to send request
              uses: actions/github-script@v6
              with:
                script: |
                    const axios = require('axios')
                    const res = await axios('https://icanhazdadjoke.com', {headers: {
                        Accept: 'text/plain'}})
                    console.log(res.data)

            
              
