name: cashing and artifact

on: [workflow_dispatch]

jobs:
    use-axios:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 #installing axios so its avaialbe in next steps
            - name: use cache action
              id: cache
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: ${{ runner.os }}-npm-cache-${{hashFiles('**/package-lock.json')}} #linux-npm-cache#12312412 some random hash that will change and depends on runner
                restore-keys: |
                    ${{ runner.os }}-npm-cache-
                    ${{ runner.os }}
            - name: display cache
              run: echo '${{toJson(steps.cache.outputs)}}'
            - name: install dependency
              run: npm install 
            - name: run tests #we added testing here
              run: npm test
            - name: upload a coverage report
              uses: actions/upload-artifact@v3
              if: always()
              with:
                name: code-coverage
                path: coverage
                retention-days: 10 # keep it for 10 days
            - name: Use Axios # axios is use to send request
              uses: actions/github-script@v6
              with:
                script: |
                    const axios = require('axios')
                    const res = await axios('https://icanhazdadjoke.com', {headers: {
                        Accept: 'text/plain'}})
                    console.log(res.data)

            
              
