name: checkout-repo-action

on: [push]

jobs:
    check-job-name:
        runs-on: ubuntu-latest
        steps:
            - name: list items before
              run: ls -ltr
            - name: checkout
              uses: actions/checkout@v3
            - name: list items after
              run: ls -ltr
