name: Concurrency 1

run-name: Concurrency2 - ${{inputs.environment}}
on:
    workflow_dispatch:
        inputs:
            string:
                type: string
                description: asd
                required: true
            environment:
                description: "Prod environment"
                type: environment
                required: true
concurrency: 
    group: concurrency-'${{inputs.environment}}' #this is called concurrency group this will guarantee it will only work one time
    cancel-in-progress: true
jobs:
    concurrency1-test:
        runs-on: ubuntu-latest
        steps:
            - name: sleep
              run: sleep 30
            - name: echo
              run: |
                echo '${{inputs.string}}'
                echo '${{inputs.environment}}'
                echo "concurrency-'${{inputs.environment}}'"
