name: decryption worfklow
 
on: push

jobs:
    decryption-job:
        runs-on: ${{vars.JOBS_RUNNER}}
        env:
            PASSPHRASE: ${{ secrets.PASSPHRASE}}
        steps:
            - uses: actions/checkout@v3
            - name: decrypt token
              run: |
                mkdir $HOME/secrets
                gpg --quiet --batch --yes --pinentry-mode=loopback --decrypt --passphrase="$PASSPHRASE" --output $HOME/secrets/secret.json encrypt-data.json.gpg
