name: Environment variables

on: [push]

env:
    WF_LEVEL_ENV: environment Variable on Workflow level

jobs: 
    type-environment-var:
        runs-on: ubuntu-latest
       #if: $GITHUB_REF == 'refs/heads/main' DONT USE THIS
        if: github.ref == 'refs/heads/main'
        steps:
            - name: display env variable
              run: echo $GITHUB_REF
    type-context-var:
        runs-on: ubuntu-latest
        env:
            JOB_LEVEL_ENV: environemnt Variable on Job Level
        if: github.ref == 'refs/heads/main'
        steps:
            - name: display context variable
              run: echo '${{github.ref}}'
            - name: set env vars
              run: |
                echo "NEW_ENV_VAR=$(date)" >> "$GITHUB_ENV"
                echo "JOB_LEVEL_ENV=$RANDOM" >> "$GITHUB_ENV"
            - name: multiline env var
              run: |
                DELIMITER=1234
                echo "RANDOM_JOKE<<$DELIMITER" >>"$GITHUB_ENV"
                echo "Here is a joke: ">> "$GITHUB_ENV"
                curl -s "https://icanhazdadjoke.com/" >> "$GITHUB_ENV"
                echo "" >> "$GITHUB_ENV"
                echo "$DELIMITER" >> "$GITHUB_ENV"
            - name: log env var
              env:
                STEP_LEVEL_ENV: Environment Variable on step Level
                WF_LEVEL_ENV: Override Workflow Variable
              run: |
                echo '${{ env.JOB_LEVEL_ENV }}'
                echo $JOB_LEVEL_ENV
                echo $STEP_LEVEL_ENV
                echo $WF_LEVEL_ENV
                echo $NEW_ENV_VAR
                echo $RANDOM_JOKE
