name: docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container: 
            image: node:24-alpine3.20
            # credentials:
            # username:
            # password we can add those as credentials
            env:
                API_URL: someurl.com
            ports:
                - 80
            # volumes:
            #     - vol_name:/path/in/container
            #     - /path/to/containerS
            #     - /path/in.host:/path/in/container we can add also volumes
            options: --cpus 1 #any option that you can pass to dokcer create command
        steps:
            - name: Log Node & Os Versions
              run: |
                node -v
                cat /etc/os-release
            - name: log environemnt variable
              run: |
                echo $API_URL
            - name: Create  file
              run: echo 'Some text' >>text.txt # this is going to run in working director of the first container which is mapped to adirectory in our running machine
                                               # this file will be shared so even other docker containers are abl to access them
            - name: Container in step
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: /usr/local/bin/node
                args: -p 2+3
            - name: Log node version
              uses: docker://node:18.16-alpine3.17
              with:
                args: -v
            - name: display file content
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: cat
                args: text.txt #this way it will be displayed
            - name: Checkout
              uses: actions/checkout@v3
            - name: run a script
              uses: docker://node:18.16-alpine3.17 # the container already has bash and will run the script without the need for sh as its a shell and already executable
              with:
                entrypoint: ./script.sh
                args: "Some String" #Some is first argument String is second argument
