name: checking events

on:
    push:
    pull_request:
    issues: 
        types: [opened, edited, closed]

jobs:
    display-data:
        runs-on: ubuntu-latest
        steps:
            - run: >
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v3