name: Expressions & Context

run-name: "Expression & Context by ${{ github.actor }}, event ${{github.event_name}}"
on: [push,pull_request,issues,workflow_dispatch]

jobs:
    work-with-other-expressions:
      runs-on: ubuntu-latest
      if: contains(fromJson('["pull_request","issues"]'),github.event_name)
      steps:
        - name: run only if issue has bug label
          if: contains(github.event.issue.labels.*.name, 'bug')
          run: echo ${{join(github.event.issue.labels.*.name,',')}}
    work-with-expressions-context:
        runs-on: ubuntu-latest
        steps:
            - name: Expressions
              run: |
                echo ${{1}}
                echo ${{'This is A string'}}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{1>2}}
                echo ${{'string' == 'String'}}
                echo ${{true && false}}
                echo ${{true || (false && true)}}
            - name: Dump Context
              run: |
                echo '${{ toJson(github) }}'
                echo '${{ toJson(job) }}'
                echo '${{ toJson(secrets) }}'
                echo '${{ toJson(steps) }}'
                echo '${{ toJson(runner) }}'


