name: Expressions & Context

on: [push,pull_request,issues,workflow_dispatch]

jobs:
    work-with-expressions-context:
        runs-on: ubuntu-latest
        steps:
            - name: Expressions
              run: |
                echo ${{1}}"
                echo ${{'This is A string'}}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{1>2}}
                echo ${{'string' == 'String'}}
                echo ${{true && false}}
                echo ${{true || (false && true)}}