name: Expressions & Context

on: [push,pull_request,issues,workflow_dispatch]

jobs:
    work-with-expressions-context:
        runs-on: ubuntu-latest
        steps:
            - name: echo a context variable
              id: greet
              uses: actions/hello-world-javascript-action@main
              with:
                who-to-greet: "Mohammed"
            - name: log greeting time
              run: echo "${{steps.greet.outputs.time}}"