name : external event repo

on:
  repository_dispatch:
    types: [build]
jobs:
  echo-astring:
    runs-on: ubuntu-latest
    steps:
      -  name: echo a string
         run: echo ${{github.event.client_payload.env}}