name: first-workflow

on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest # for last version i added -latest
        steps:
            - name: echo a string #This is an arrray of jobs
              run: echo "Hello World"
            - name: multilinecommand
              run : |
                node -v
                npm -v
    parallel-job:
      runs-on: macos-latest
      steps:
            - name: display Os
              run: sw_vers
    dependent-job:  
      runs-on: windows-latest
      needs: run-shell-commands # this can be an Array
      steps:
            - name: echo A string 
              run: Write-Output "Windows String"
            - name: Error Step
              run: does not exist