name: open issue

on: 
    workflow_dispatch:
        inputs:
            title:
                type: string
                description: title
                required: true
            body:
                type: string
                description: body
                required: true
        
jobs:
    call-public-action:
        runs-on: ubuntu-latest
        steps:
            - name: call the action
              uses: Mohammed-Rifaii/js-action@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                title: ${{inputs.title}}
                body: ${{inputs.body}}

