name: open issue
permissions:
  contents: read
  issues: write
on: 
    workflow_dispatch:
        inputs:
            title:
                type: string
                description: title
                required: true
            body:
                type: string
                description: body
                required: true
        
jobs:
    call-public-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: call-action
              id: call-action
              uses: Mohammed-Rifaii/js-action@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                title: ${{inputs.title}}
                body: ${{inputs.body}}
            - name: Show issue output
              run: echo "${{steps.call-action.outputs.issue}}"

