name: Adding A Comment in js using action

on: 
   pull_request_target:
        types: [opened]

jobs:
    writing-A-Comment:
        runs-on: ubuntu-latest
        steps: 
            - name: pr A comment
              uses: actions/github-script@v6
              with:  #this one is for params
                script: |
                    github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: 'Thanks for contributing',
                    });
