name: Schedule test

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Scheduled job ran at $(date)"