name: simple-action

on: [push]

jobs:
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v3
            - name: Send A Slack joke
              uses: ./.github/actions/slack-joke
              id: slack-joke
              with:
                slack_username: Test
                upload_joke: true
                slack_webhook: ${{secrets.SLACK_WEBHOOK}} # in env variables
            - name: display joke
              run: echo '${{steps.slack-joke.outputs.joke}}'


#we give it actions/directory-for-action-used-on-github+ branch(the branch where we git from) 
#we can also use docker or docker image
#or we can use uses: actions/hello-world-javascript-action@v1.1.2 pr v1
#we can use it with id will mention screenshot how to get them ex @9e4b6280010b48928905c91e5b1e6603cea947aa
#with params will be mentioned in the action page