name: Caller workflow

on:
    workflow_dispatch:
        inputs:
            name:
                description: " input description"
                type: string
                default: 'mohammed'
                required: false

jobs:
    calling-a-reusable-workflows-in-diff-repo:
        uses: Kami-Kode/workflows-test/.github/workflows/reusable-workflow.yml@main
        with:
            name: '${{inputs.name}}'
        secrets: 
            access-token: '${{secrets.ACCESS_TOKEN}}' #to use this in later workflows we need to add it everytime to the job
    calling-a-reusable-workflows-in-same-repo:
        uses: ./.github/workflows/reusable-workflow.yml # to use this  #wihtout branch since on the same branch i think
        secrets: inherit  #to inherit the secrets from caller and sent it to the reusable-workflow
    using-resuable-wf-outputs:
        runs-on: ubuntu-latest
        needs: calling-a-reusable-workflows-in-same-repo
        steps:
            - run: echo ${{needs.calling-a-reusable-workflows-in-same-repo.outputs.date}}