name: vars and secrets

on:
    push:
    workflow_dispatch:

jobs:
    run-on-ubuntu:
        runs-on: ${{ vars.JOBS_RUNNER }}
        environment: "Prod Environment"
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET}} # im setting into a variable here but i can directly use them
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
            ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}
        steps:
            - name: run only if Boolean Secret is true
            #we cant access it using environment variable but through context env.
              if: env.BOOLEAN_SECRET == 'true' 
              run: echo "I ran cause its true"
            - name: logging vars
              run: |
                echo $BOOLEAN_SECRET
                echo $ENV_LEVEL_VAR
                echo $REPO_LEVEL_VAR
                echo $ORG_LEVEL_VAR
