name: workflow-commands

on: [push]

jobs:
    command-to-do:
        runs-on: ubuntu-latest
        steps:
            - name: Setting Some error message
              run: "::error:: missing semi column"

